### ISSUE TITLE
kicad project files or equivalent to adjust for MX spacing

### ISSUE THREAD

**Issue by suriaribeiro** [JonMuller/gerbers#14]
I really like this PCB but unfortunately due to my large hands I can only handle MX spaced keys.  Do you happen to have a version with choc switches that is MX spaced? Alternatively if you don't mind sharing the Kicad project files I can give a go at spacing out the switches. 

Thanks!

**Comment by JonMuller** [comment]
Hi there!

Great question!! I think at one point I did do an MX spaced version. Let me look around when I have time tonight. There's a reasonable chance that the MX version had some routing issues though. Not that they couldn't be easily fixed, I just can't remember if I did fix that. I think I had the controllers oriented in a different way too. I'll look. If I don't respond fast enough (it's not intentional, trust me!!) it would probably be easier for you to just grab the standard corne kicad files and remove anything related to the regular controller and add in the XIAO. I think my footprint is semi custom though. I have to figure out how to put that on here somewhere. I have a couple of different versions. I used one not too long ago that requires surface mount but drops out all the jumpers needed for making a reversible PCB. 

Alternatively, the Tenax project is MX spaced. It's not that different really, just uses some splay and a slightly more aggressive stagger. It's a little more expensive to have made though because it's not reversible, so the overall PCB is bigger, but you do get a full board with each, so the minimum will still net you 5 total boards.

**Comment by suriaribeiro** [comment]
Thanks for the quick reply. Your Tenax keyboard is also great, specially the splay. However, I am keen to build a keyboard with a 6th collumn and your corne keyboard is perfect for that. In any cass, if you don't have an mx ready version but are happy to share the editable files I could give it a go in kicad

**Comment by JonMuller** [comment]
I don't know why I always forget that not everyone wants the 5 column version. That reminded me that the problem with the MX version was that when you snapped off the outer column, it created an island on the ground plane, so I had to bodge some stuff. Not an issue if you leave the last column on. But I may have fixed it. 

You're not by any chance in the United States, are you?

**Comment by JonMuller** [comment]
Ok, I found the actual boards. I realize there's another possible issue with them... I designed them to have integrated displays, so you'd have to find yourself some bare displays (aliexpress has always been hit or miss for me) that work. The issue with the ground plane mostly impacted the displays. If you don't care about displays (and I'm only talking about the super low powered ones, like the ones used in a Nice!View) then it's even less of a concern. I also don't know that I have a great case file to share. 

Just some extra info for you.

**Comment by suriaribeiro** [comment]
Hi Jon,

Thanks for getting back to me. I am based in Berlin, Germany. Whilist a display would be nice, it is certainly no strictly needed. 
With all that said, I was thinking about potentially adding a splay on the last 2 collumns, therefore a way to eventually edit the files would be great.

**Comment by suriaribeiro** [comment]
Hi Jon, this is the board layout I was hoping to build. I really like how you went about creating the bridges to make the board reversible and would love to re-use your schematic. If for whatever reason you do no wish to share the editable files perhaps I can commission you to create gerber files using this layout? 
[airus_kbd.dxf.zip](https://github.com/JonMuller/gerbers/files/12909733/airus_kbd.dxf.zip)

looking forward to your reply

**Comment by JonMuller** [comment]
Hi suriaribeiro, 
I'm not against sharing editable files, the problem here is me and the way I went about things. I don't know that I have them in an easily shareable format. The problem is the way I went about my libraries. I believe if I shared the files as is, the libraries would get lost and then as soon as you edit them, you would be left in the position of either having to build certain footprints from scratch or they may completely disappear all together. I really need to learn how to do this better.

Let me just make sure I understand what you're after though.
1. MX Space/switch compatibility
2. Layout matching the file you shared above
3. Reversible PCB
4. XIAO BLE compatibility?

Outside of that, what else are you expecting?
Hotswap for switches?
Display options?
What type of battery connector?
Power switches?

Anything else I'm missing?

Also, if you were to have the PCBs made, would you want any assembly done at the manufacturer? I have often let them handle the diodes. Makes it easier to use smaller SMD diodes since I don't have to worry about soldering them. But I usually have an optional through hole mount in case a diode gets knocked off or just needs to be replaced. Much easier to do that by hand. 

As far as reversible PCBs go, I have 2 designs that I've done. The one with all the jumpers and one where I don't use through holes on the controllers, so they must be surface mounted. That can be seen here: https://www.reddit.com/r/ErgoMechKeyboards/comments/1456utk/little_more_xiao_ble_trouble/  There are pros and cons to each way. One does require a lot less soldering though.

**Comment by suriaribeiro** [comment]
Hi Jon, someone created an mx version. Will close the issue making reference to this alternative design.
https://github.com/friction07/corne-xiao/tree/main/rev1
